name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v3
      - run: gradle buildPlugin --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/distributions/*.zip
